language: python

python:
    - "3.6"

install:
    # install Version 0.51 de Hugo
    # - wget $(wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}')
    - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments
    - rm -rf docs 2> /dev/null

script:
    - hugo -F
    - mkdir docs
    - echo 'ww2.profesor-p.com' > docs/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GITHUB_EMAIL
  verbose: true
  keep-history: true
  local-dir: docs
  target_branch: master  # branch contains blog content
  on:
    branch: source  # branch contains Hugo generator code