baseURL = "/"
languageCode = "es-ES"
defaultContentLanguage = "es"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

[outputs]
home = [ "HTML", "RSS", "JSON"]




[Languages.es]
title = "Documentacion en español"
weight = 2
languageName = "Español"

[[Languages.es.menu.shortcuts]]
name = "<i class='fab fa-fw fa-phone'></i>Contacto"
identifier = "ds"
url = "/contacto"
weight = 10

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i>Acerca de"
url = "/acerca"
weight = 11

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i>Experiencia Laboral"
identifier = "hugodoc"
url = "/experiencia_laboral"
weight = 20

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Anjelica"
url = "/anjelica"
weight = 30
