baseURL = "http://ww2.profesor-p.com/"
languageCode = "es-ES"
defaultContentLanguage = "es"
enableEmoji = true
title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "docs"

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = false
  disableLanguageSwitchingButton=true
  
[outputs]
home = [ "HTML", "RSS", "JSON"]




[Languages.es]
title = "Documentacion en español"
weight = 2
languageName = "Español"

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i>Últimas entradas"
url = "/last"
weight = 0

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i>Acerca de"
url = "/acerca"
weight = 10


[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bolt'></i> Anjelica"
url = "/anjelica"
weight = 20


