baseURL = "http://www.profesor-p.com/"
languageCode = "es-ES"
defaultContentLanguage = "es"
enableEmoji = true
title = "Blog del Profesor-P"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "docs"

[params]
  editURL = "https://github.com/chuchip/profesor-p"
  description = "Articulos sobre informática "
  author = "Jesus J. Puente"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLanguageSwitchingButton=true
  
[outputs]
home = [ "HTML", "RSS", "JSON"]




[Languages.es]
title = "Documentacion en español"
weight = 2
languageName = "Español"

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i>Últimas entradas"
url = "/last"
weight = 0

[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-camera'></i>Acerca de"
url = "/acerca"
weight = 10


[[Languages.es.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bolt'></i> Anjelica"
url = "/anjelica"
weight = 20


